# Ultralytics YOLO 🚀, AGPL-3.0 license
# YOLO tracker settings for BoT-SORT tracker https://github.com/NirAharon/BoT-SORT

# These are the default settings BEFORE the Oct 2024 commit decreasing the thresholds:
# https://github.com/ultralytics/ultralytics/commit/aabd0136ec40223cf423847635a2a4de95bba63d
# They seem to work better for this task.

tracker_type: botsort # tracker type, ['botsort', 'bytetrack']
track_high_thresh: 0.5 # threshold for the first association
track_low_thresh: 0.1 # threshold for the second association
new_track_thresh: 0.6 # threshold for init new track if the detection does not match any tracks
track_buffer: 30 # buffer to calculate the time when to remove tracks
match_thresh: 0.8 # threshold for matching tracks
fuse_score: True # Whether to fuse confidence scores with the iou distances before matching
# min_box_area: 10  # threshold for min box areas(for tracker evaluation, not used for now)

# BoT-SORT settings

# We allow the user to choose the GMC method, including custom ones e.g. RAFT.
# We do this by replacing the stock GMC class via monkeypatch
# and the `gmc_method` config parameter is never used (see gmc_patch in tracking.py)
gmc_method: overridden
# ReID model related thresh (not supported yet)
proximity_thresh: 0.5
appearance_thresh: 0.25
with_reid: False
